name: Test Code

on: [push, pull_request]

env:
  node_version: 12.14.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - run: npm ci
      - run: npm test
        env:
          CI: true