name: E2E
on: [push]

jobs:
  e2e:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: avalanchejs
      - uses: actions/checkout@v2
        with:
          repository: ava-labs/avalanchego
          path: avalanchego
          ref: master
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: avalanchejs
          node-version: '14'
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15'
      - run: |
          cd avalanchejs
          yarn install --frozen-lockfile
      - run: |
          cd avalanchego
          ./scripts/build.sh
      - run: |
          pwd
          ls
