name: E2E
on: [push]

jobs:
  e2e:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: '14'
      - run: yarn install --frozen-lockfile
