name: E2E
on: push

jobs:
  e2e:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout AvalancheJS
        # Uses the major version of a release of a public repository
        uses: actions/checkout@v2
        # with ava-labs/avalanchejs
      - name: Checkout AvalancheGo
        uses: actions/checkout@v2
        with:
          repository: 'ava-labs/avalanchego'
          ref: ${{ github.ref == 'refs/heads/master' && 'master' || 'dev' }}
          path: 'avalanchego'
      - name: Checkout Avash
        uses: actions/checkout@v2
        with:
          repository: 'ava-labs/avash'
          ref: ${{ github.ref == 'refs/heads/master' && 'master' || 'dev' }}
          path: 'avash'
      - name: Setup Node Version and Cache
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: '14'
      - name: Install NodeJS dependencies
        run: yarn install --frozen-lockfile
      - name: Setup Golang Version
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.8'
      - name: Static compilation of avalanchego
        run: |
          sudo apt-get install musl-tools
          cd avalanchego
          STATIC_COMPILATION=1 ./scripts/build.sh && pwd
      - name: Static compilation of avash
        run: |
          cd avash
          STATIC_COMPILATION=1 go get && 
          go build && 
          pwd &&
          echo "avalancheLocation" >> my_file.txt &&
          cat my_file.txt &&
          ./avash runscript scripts/five_node_staking.lua
      - name: AvalancheJS E2E Test
        env: 
          AVALANCHEGO_IP: localhost
          AVALANCHEGO_PORT: 9650
        run: yarn test -i --roots e2e_tests
